spring.application.name=sidetracked-api

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/sidetracked
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true